import {Inter, Raleway, Radio_Canada} from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import {Provider} from "react-redux";
import store from "@/app/store/store";
import StoreProvider from "@/app/StoreProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="ru">
        <StoreProvider>
            <body className={inter.className}>
            <Header/>
            {children}
            <Footer/>
            </body>
        </StoreProvider>
        </html>
    );
}
